[package]
name = "globtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.5"
regex = "1.9.5"
tokio = { version = "1.32.0", features = ["rt", "macros", "fs"] }
