[tool.poetry]
name = "richtest"
version = "0.1.0"
description = ""
authors = ["Julio Biason <julio.biason@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^13.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
